<?php

namespace App\Traits;

use Illuminate\Support\Str;

/**
 * Every table's id is a UUID generated by whoever creates the record first.
 * On a POS terminal that's the frontend (crypto.randomUUID()) before it's
 * ever synced — this trait only fills one in when nothing was set already,
 * which covers records created directly through the API (admin app,
 * seeders) without breaking the offline-origin case.
 */
trait HasUuid
{
    public $incrementing = false;
    protected $keyType = 'string';

    protected static function bootHasUuid(): void
    {
        static::creating(function ($model) {
            $key = $model->getKeyName();
            if (empty($model->{$key})) {
                $model->{$key} = (string) Str::uuid();
            }
        });
    }
}
